config/routes.rb
SfOverflow::Application.routes.draw do
  root :to => 'questions#index'

  resources :users, :except => :index
  resource :session, :only => [:create, :destroy, :new]
  
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :questions, :answers do
    post '/upvote' => 'votes#upvote'
    post '/downvote' => 'votes#downvote'
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :description, :user_id

  belongs_to :user
  has_many :answers, :as => :answerable
  has_many :votes, :as => :votable

  validates :title, :presence => true
  validates :title, :uniqueness => true
  validates :description, :presence => true

  def sum_votes
    Vote.where("votable_id = ? AND votable_type = 'Question'", self.id).sum('counter')
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
    @question = Question.new
    @user = User.new
  end

  def create
    @question = Question.new(params[:question])
    @question.update_attributes(:user_id => session[:id])
    @question.save
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def show
    p params
    @question = Question.find(params[:id])
    @answers = Answer.where(:question_id => @question.id)
    @answer = Answer.new
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(params[:question])
    redirect_to @question
  end

  def destroy
    question = Question.destroy(params[:id])
    Answer.where(:question_id => question.id).destroy_all
    @user = User.find(session[:id])
    redirect_to @user
  end
end

app/views/questions/_display_all_questions.html.haml
- answers.each do |answer|
  = render '/answers/answer_votes', :answer => answer
  = render '/answers/answer_description', :answer => answer, :question => question

app/views/questions/_new_question.html.haml
%li
  #{link_to question.title, question} 
  %br
  #{link_to "Edit", edit_question_path(question)}
  %br
  #{link_to "Delete", question_path(question), :method => :delete}
  %br

app/views/questions/_profile_questions.html.haml
.questions_any
  -if users_questions.any?
    %h3 Your Questions

  %ul{:class=>"profile_questions"}
    - @users_questions.reverse.each do |question|
      = render '/questions/new_question', :question => question

app/views/questions/_question_form.html.haml
.new_question_form
  = form_for @question, :remote =>true do |form|
    = form.label :question_title, "Question Title:"
    = h form.text_field :title
    = form.label :question, "Question:"
    = h form.text_field :description
    = form.submit

app/views/questions/_question_info.html.haml
%h1 #{ question.title }
%p #{question.description}

app/views/questions/_question_voting.html.haml
.voting_info
  .vote_count
    %span{:id=>"question-vote"}
      VOTES #{question.sum_votes}


  %span{:class=>"question-button-up"}
    = button_to "Upvote", question_upvote_path(question)

  %span{:class=>"question-button-down"}
    = button_to "Downvote", question_downvote_path(question)

app/views/questions/create.js.erb
<% if @question.errors.present? %>
  $('ul.profile_questions').before("<%= @question.errors.full_messages.join(', ')%>");
<% else %>
  $('ul.profile_questions').prepend("<%= j render "/questions/new_question", :question => @question %>");
<%end%>

app/views/questions/destroy.html.haml
delete.html.haml

app/views/questions/edit.html.haml
= render 'questions/question_form', :locals => @question

app/views/questions/index.html.erb
<h1> SF Overflow </h1>

<%= render "users/loginform" %>
<%= render "users/signup_form" %>

<iframe src="http://mapsengine.google.com/map/view?mid=zYPZELugC5y0.kteJpst9-ta0" width="640" height="480"></iframe>

<ul class="question_display">
  <% @questions.each do |question| %>
    <li><p><%= link_to question.title, question %></p></li>
  <% end %>
</ul>

app/views/questions/index.html.haml
%h1 Move SF 

- if flash[:error]
  .error 
    %p= h flash[:error] 

#map-canvas{:style=>"width: 800px; height: 400px"}

%h3 Open Questions
%ul{:class => "question_display"}
- @questions.each do |question|
  %li #{link_to question.title, question}

%h3 News Feed
- retrieve_craigslist_data.each do |rental|
  = link_to rental[0], rental[2]
  %br
  = rental[1]
  %br
  = rental[3]
  %br
  %br

app/views/questions/new.html.haml
= render '/questions/question_form', :locals => @question

app/views/questions/show.html.erb
<%= render 'question_voting', :question => @question %>
<%= render 'question_info', :question => @question %>
<%= render 'answers/answer_to_question_form', :question => @question %>

 <!-- MOVE ME TO A HELPER, BUT MAKE SURE THAT DOING SO DOESN'T BREAK LE CODE -->
<% def print_answers_for(id) %> 
  <% @answers.each do |answer| %>
    <% if answer.answerable_id == id && answer.answerable_type == "Answer" %>
      <%=  answer.description %><br>
        <%= render 'answers/answer_to_answer_form', :answer => answer, :question => @question %>
      <% print_answers_for(answer.id) %>
    <% end %>
  <% end %>
<% end %>
<!--  -->

<% @answers.each do |answer| %>
  <% if answer.answerable_type == "Question" %>
    <%= answer.description %><br>
    <%= render 'answers/answer_to_answer_form', :answer => answer, :question => @question %>
    <% print_answers_for(answer.id) %>
  <% end %>
<% end %>

app/views/questions/update.html.haml
update.html.haml