config/routes.rb
SfOverflow::Application.routes.draw do
  root :to => 'questions#index'

  resources :users, :except => :index
  resource :session, :only => [:create, :destroy, :new]
  
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :questions, :answers do
    post '/upvote' => 'votes#upvote'
    post '/downvote' => 'votes#downvote'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :email, :name, :provider, :uid
  
  has_secure_password

  has_many :questions
  has_many :answers
  has_many :votes

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :username, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def create
    @user = User.create(params[:user])
    if @user.id.nil?
      redirect_to root_path, :flash => { :error => "Invalid username, email or password." }
    else 
      session[:id] = @user.id
      redirect_to @user
    end
  end

  def new
    @user = User.new
  end

  def edit

  end

  def show
    @user = User.find(session[:id])
    @users_questions = Question.where(:user_id => @user.id)
    @users_answers = Answer.where(:user_id => @user.id)
    @question = Question.new
  end

  def update

  end

  def destroy
  end

end

app/views/users/_loginform.html.haml
.login_form
  = link_to image_tag('facebook-login-button.png'), 'http://localhost:3000/auth/facebook'
  = form_tag new_session_path, :method => 'get' do
    = h text_field_tag :username, nil, :placeholder => "username"
    %br
    = h password_field_tag :password, nil, :placeholder => "password" 
    %br
    = submit_tag("Submit")

app/views/users/_signup_form.html.haml
.signup_form
  = form_for @user do |form|
    = h form.text_field :username, :required => true, :placeholder => :username
    = h form.text_field :email, :required => true, :placeholder => :email 
    = h form.password_field :password, :required => true, :placeholder => :password 
    = form.submit

app/views/users/create.html.erb
"it works"

app/views/users/create.html.haml
"it works"

app/views/users/delete.html.erb
delete.html.erb

app/views/users/delete.html.haml
delete.html.erb

app/views/users/edit.html.haml
edit.html.haml

app/views/users/new.html.haml
= render 'users/signup_form'

app/views/users/show.html.haml
%h2 Welcome, #{@user.username.capitalize}

.submit_question
  = link_to "Submit a Question", new_question_path

.question_form
  = render '/questions/question_form', :locals => @question

= render '/questions/profile_questions', :users_questions => @users_questions 
= render '/answers/profile_answers', :users_answers => @users_answers