config/routes.rb
SfOverflow::Application.routes.draw do
  root :to => 'questions#index'

  resources :users, :except => :index
  resource :session, :only => [:create, :destroy, :new]
  
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :questions, :answers do
    post '/upvote' => 'votes#upvote'
    post '/downvote' => 'votes#downvote'
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :description, :user_id, :answerable_type, :answerable_id, :question_id

  belongs_to :user
  belongs_to :answerable, :polymorphic => true
  has_many :answers, :as => :answerable
  has_many :votes, :as => :votable

  validates :description, :presence => true

  def sum_votes
    Vote.where("votable_id = ? AND votable_type = 'Answer'", self.id).sum('counter')
  end

  def get_children
    Answer.where(:answerable_id => self.id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    puts "*" * 50
    p params[:answer]
    @answer = Answer.create(params[:answer])
    @answer.update_attributes(:user_id => session[:id], 
                              :answerable_type => params[:answer][:answerable_type], 
                              :answerable_id => params[:answer][:answerable_id].to_i, 
                              :question_id => params[:answer][:question_id])
    @question = Question.find(@answer.question_id)
    redirect_to @question
  end

  def new
    @answer = Answer.new
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = Question.find(@answer.question_id)
  end

  def show
    @answer = Answer.find(params[:id])
    @question = Question.find(@answer.question_id)
    redirect_to @question
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update_attributes(params[:answer])
    redirect_to @answer
  end

  def destroy
    Answer.destroy(params[:id])
    @user = User.find(session[:id])
    redirect_to @user
  end

end

app/views/answers/_answer_description.html.erb
<p>Comment: 
  <%= answer.description %>
</p>

<%= render '/answers/answer_form', :answer => answer, :answerable => answer, :question => question %>

app/views/answers/_answer_to_answer_form.html.erb
<div class="answer_form">
  <%= form_for Answer.create do |form| %>
    <p><%= form.label :answer, "Answer:" %></p>
    <%= h form.text_field :description %><br>
    <%= form.hidden_field :answerable_type, :value => "Answer" %>
    <%= form.hidden_field :answerable_id, :value => answer.id %>
    <%= form.hidden_field :question_id, :value => question.id %>
    <%= form.submit "Submit Answer" %>
  <% end %>
</div>

app/views/answers/_answer_to_question_form.html.erb
<div class="answer_form">
  <%= form_for Answer.create do |form| %>
    <p><%= form.label :answer, "Answer:" %></p>
    <%= h form.text_field :description %><br>
    <%= form.hidden_field :answerable_type, :value => "Question" %>
    <%= form.hidden_field :answerable_id, :value => question.id %>
    <%= form.hidden_field :question_id, :value => question.id %>
    <%= form.submit "Submit Answer" %>
  <% end %>
</div>

app/views/answers/_answer_votes.html.erb
<span class="answer-vote">
  Comment Votes: 
  <%= answer.sum_votes %>
  <%= button_to "Upvote", answer_upvote_path(answer) %>
  <%= button_to "Downvote", answer_downvote_path(answer) %>
</span>

app/views/answers/_display_all_answers.html.erb
<% answer_answers = [] %>
<% question_answers = [] %>

<% answers.each do |answer| %>
  <% question_answers << answer if answer.answerable_type == "Question" %>
  <% answer_answers << answer if answer.answerable_type == "Answer" %>
<% end %>

<% answer_answers.sort_by!{|answer| answer.answerable_id} %>
<% question_answers.sort_by!{|answer| answer.id} %>

<% question_answers.each do |qanswer| %>
  <%= render '/answers/answer_votes', :answer => qanswer %>
  <%= render '/answers/answer_description', :answer => qanswer, :question => question %>
  <% answer_answers.each do |aanswer| %>
    <% if qanswer.id == aanswer.answerable_id %>
      <div class="answer">
        <%= render '/answers/answer_votes', :answer => aanswer %>
        <%= render '/answers/answer_description', :answer => aanswer, :question => question %>
      </div>
    <% end %>
  <% end %>
<% end %>





<!-- 
ignore
<#% answers.each do |answer| %>
  <div class="answer">
    <#%= render '/answers/answer_votes', :answer => answer %>
    <#%= render '/answers/answer_description', :answer => answer, :question => question %>
  </div>
<#% end %> -->

app/views/answers/_profile_answers.html.erb
<% if users_answers.any? %>
  <h3>Your Answers</h3>
<% end %>

<div class="profile_answers">
  <% users_answers.each do |answer| %>
    <%= link_to answer.description, answer %> 
    <%= link_to "Edit", edit_answer_path(answer) %>
    <%= link_to "Delete", answer_path(answer), :method => :delete %>
    <br><br>
  <% end %>
</div>

app/views/answers/delete.html.erb
delete.html.erb

app/views/answers/edit.html.erb
<%= render 'answer_form', :locals => [@answer, @question] %>

app/views/answers/show.html.erb
show.html.erb

app/views/answers/update.html.erb
update.html.erb